platform :ios, '9.0'

require_relative '../scripts/autolink-ios'

if ENV['USE_FRAMEWORKS'] == '1'
  puts "Installing pods with use_frameworks!"
  use_frameworks!
end

def pods()
  project 'RNTesterPods.xcodeproj'
  
  # Enable TurboModule
  use_react_native!(path: "..", turbo_modules_enabled: true)
  pod 'React-turbomodule-samples', :path => '../ReactCommon/turbomodule/samples'

  # Additional Pods which aren't included in the default Podfile
  pod 'React-RCTCameraRoll', :path => '../Libraries/CameraRoll'
  pod 'React-ART', :path => '../Libraries/ART'
  pod 'React-RCTPushNotification', :path => '../Libraries/PushNotificationIOS'

  # Additional Pods which are classed as unstable
  #
  # To use fabric: add `fabric_enabled` option to the use_react_native method above, like below
  # use_react_native!(path: "..", turbo_modules_enabled: true, fabric_enabled: true)
end
